morpho-org/morpho-blue-api-metadata

data/tokens.json

https://morpholabs.slack.com/archives/C07G53ZCV5K/p1737922362203939

fix(tokens): add eth tag for base WETH

---

data/price-feeds.json

feat(MEV): clearing PT-wstUSR and wstUSR markets

---

data/oracle-prices.json
data/tokens.json
data/vaults-whitelist.json

- XAUT is following the same structure as the XAUM (matrixdock) for pricing + whitelisting! 
fixes INTEG-1528
fixes INTEG-1529
fixes INTEG-1530

feat(whitelisting): adding 3 vaults, 1 token and pricing it

---

data/oracle-prices.json
data/tokens.json
data/vaults-whitelist.json

DO NOT MERGE -> TBMerge only if 0 timelock pass
mergeable

feat(solvbtc.bbn): whitelisting vault and asset + pricing

---

data/price-feeds.json
data/tokens.json
data/vaults-whitelist.json

The mBASIS tokens are not priced yet.
not on Mainnet nor Base. 
We have to add the support of the midas-type of oracle, but at least the vault and token is recognized with this pr
fixes INTEG-1533

feat(mBASIS): whitelisting mBASIS token and gauntlet vault

---

data/oracle-prices.json
data/tokens.json
data/vaults-whitelist.json

I hardcoded them in oracle price, thus we are adding the tag "hardcoded" which is for rewards team to handle that they should not be eligible for rewards, given i can't price USDQ nor USDR onchain.
fixes INTEG-1532 also
Mergeable!

feat(steakhouse-batch2): whitelisting and pricing, no rewards for USDR and USDQ

---

data/oracle-prices.json
data/price-feeds.json
data/tokens.json
data/vaults-whitelist.json

- Vault whitelisted
- Preparing the (s)deUSD token pricing/whitelisting

feat(gauntlet-elixir vault): whitelisting vault

---

data/vaults-whitelist.json

feat(Seamless): whitelisting base gauntlet ETH curated vault

---

data/tokens.json

Don't have any tag in mind... do you?

feat(WELL): adding the logo for the well token

---

data/curators-whitelist.json
data/oracle-prices.json
data/price-feeds.json
data/tokens.json
data/vaults-whitelist.json

feat(apostro): merging 2 base vault

---

data/curators-whitelist.json
data/vaults-whitelist.json

feat(Alphaping): whitelsiting Aphaping aUSDC and aWETH vaults

---

data/curators-whitelist.json
data/vaults-whitelist.json

Curator ===owner 
timelock = 1 day

feat(hyperithm): whitelisting hyperithm vault

---

data/vaults-whitelist.json

feat(MEV): whitelisting 2 MEV vaults

---

data/oracle-vaults.json
data/tokens.json

Already priced in the api. When that is the case, no need to reprice it

feat(ynETHx): whitelisting + whitelisting feed

---

data/curators-whitelist.json
data/vaults-whitelist.json

TODO:
- Timestamp for the 7th of March ✅ 
- Need to validate the curator address in the curator list [edit: validated] ✅

feat(hakutora): preparation of the vault whitelisting

---

data/oracle-prices.json
data/price-feeds.json
data/tokens.json

feat(SPARK): whitelisting and pricing new PT market

---

data/curators-whitelist.json
data/oracle-prices.json
data/oracle-vaults.json
data/price-feeds.json
data/spot-prices.json
data/tokens.json
data/vaults-whitelist.json
docs/pricing/oracle-prices.md

also 
fixes INTEG-1892
fixes INTEG-1879

feat(clearlabs start): whitelisting vault & markets clearance

---

data/price-feeds.json
data/tokens.json
data/vaults-whitelist.json

fixes INTEG-1930
fixes INTEG-1926
fixes INTEG-1927
fixes INTEG-1928
fixes INTEG-1937

feat(apostro): whitelisting vault + markets

---

data/price-feeds.json
data/tokens.json
data/vaults-whitelist.json

fixes INTEG-1851
fixes INTEG-1862
fixes INTEG-1850
fixes INTEG-1863
fixes INTEG-1849

feat(Aphaping): 2 new vaults + markets

---

data/vaults-whitelist.json

FIXES INTEG-1981
Updating vault description

feat(desc):update MEV vault desc

---

data/price-feeds.json

Used here: https://app.morpho.org/ethereum/market/0x407d8c123443d362ffdfe73208068ef158a21d1a44a988c9acc23a51bade7905/pt-susde-29may2025-dai
validated via the oracle decoder tool

feat(feed): whitelisting oracle

---

data/price-feeds.json

fixes INTEG-1978
fixes INTEG-1979

feat(oracle): clearing one market feed

---

data/vaults-whitelist.json

feat(remove): alphaping vault

---

data/oracle-prices.json
data/oracle-vaults.json
data/spot-prices.json
data/tokens.json

FIXES INTEG-1991 - Market [cUSDOUSDC/USDC](https://app.morpho.org/ethereum/market/0x7aae9136d142aa7ec2a3ad155fb42489ed7ed93a74c589eb1643916ae19f0833/cusdousdc-usdc)
Hardcoding cUSDOUSDC pricing
FIXES INTEG-1992 - Market [cUSDO/USDC](https://app.morpho.org/ethereum/market/0x15f30b939b8590be30aa22cd8d6367cf90a0ae460ce7f644ddbf58b8442e619a/cusdo-usdc)

feat(ouroboros): cUSDO markets

---

data/oracle-prices.json
data/price-feeds.json
data/spot-prices.json
data/tokens.json

[LsETH/WETH](https://app.morpho.org/base/market/0x4dda3d40225ff86207164809ecd336f9908da885470c0526794f2064795794f3/lseth-weth)
Chainlink oracle pricing for LsETH
Chainlink LsETH feed WL
[wBLT/USDC](https://app.morpho.org/base/market/0xd1892032c68f94d2650238b363195c6c3c142ba80c0c71269d14f8ea42c0abdf/wblt-usdc)
WL feed to USD (from BMX)
Spot pricing wBLT with aerodrome slip_stream

feat(WL): wBLT and LsETH

---

data/oracle-vaults.json
data/spot-prices.json
data/tokens.json

[USDf/USDC](https://app.morpho.org/ethereum/market/0x676eca446d11a2d95a1fcd87706411ebc50c1e84916f073216150c52540d4a77/usdf-usdc)
Spot pricing USDf
[sUSDf/USDC](https://app.morpho.org/ethereum/market/0xbed987dd46049adb1ff34de8ef761a9da3b08890fa7fff629ea9b66d049de823/susdf-usdc)
Spot pricing sUSDf
Add hardcoded warning to csUSDL/USDC (0x83b7ad16905809ea36482f4fbf6cfee9c9f316d128de9a5da1952607d5e4df5e)

feat(markets):sUSDf and USDf

---

data/spot-prices.json

Reverts morpho-org/morpho-blue-api-metadata#99

Revert "fix(usdc): remove spot price"

---

data/spot-prices.json
data/tokens.json

**FIXES INTEG-2151**
Spot prices BMX token with 3 Aerodrome pools with the `aerodrome` method.
BMX -> wBLT ([pool](https://aerodrome.finance/pools?token0=0x4E74D4Db6c0726ccded4656d0BCE448876BB4C7A&token1=0x548f93779fBC992010C07467cBaf329DD5F059B7&type=-1&factory=0x420DD381b31aEf6683db6B902084cB0FFECe40Da&chain=8453) / [contract](https://basescan.org/address/0x61907C8C3E6ef7eD813aCc2fBbBf8C05ac0F31d5#code))
wBLT -> USDC ([pool](https://aerodrome.finance/pools?token0=0x4E74D4Db6c0726ccded4656d0BCE448876BB4C7A&token1=0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913&type=50&factory=0x5e7BB104d84c7CB9B682AaC2F3d509f5F406809A&chain=8453) / [contract](https://basescan.org/address/0x7cE345561E1690445eEfA0dB04F59d64b65598A8#readContract))
USDC -> WETH …

feat(pricing):BMX

---

data/oracle-prices.json
data/price-feeds.json
data/tokens.json

Note, I am slowly changing all pt-relted logo with the prefix:
Here:
https://cdn.morpho.org/assets/logos/pt-susde.svg
for all the incoming pt-susde!

feat(spark): whitelisting, pricing and clearing warning for  new pt

---

data/tokens.json
data/vaults-whitelist.json

**FIXES INTEG-2114**
[bbqWSTETH/WETH](https://app.morpho.org/ethereum/market/0x0cf0597c314f60b9e42d4666073014cf4f7cdf72dea45626aa1caad695c74f2a/bbqwsteth-weth)
Add vault token
**FIXES INTEG-2115**
[Smokehouse ETH](https://app.morpho.org/ethereum/vault/0xbEEF36A5C1372F8D7d211527FCE9f83FE02d8A73/smokehouse-eth)

feat(sh):1market-1vault

---

data/tokens.json

I confirm that asset are already priced in the API, properly

feat(logo): associating logo to asset

---

data/vaults-whitelist.json

**FIXES INTEG-2146**
[M11C-Level lvlUSD](https://app.morpho.org/ethereum/vault/0x2C3Cc1C02856894345797Cf6ee76aE76AC0f4031/m11c-level-lvlusd) whitelisting
pre-seeded ✅
3D timelock ✅

feat(M11C): vault whitelisting

---

data/price-feeds.json
test/package.json
test/scripts/feedCheck.ts

feat(decimals): updating wrong decimals on a per feed basis

---

data/oracle-vaults.json
data/price-feeds.json
data/tokens.json

fixes INTEG-2238
fixes INTEG-2239

feat(usual): clearing oracle

---

data/price-feeds.json
data/tokens.json

fixes INTEG-2250
fixes INTEG-2248

feat(MEV): oracle and market clearance

---

data/vaults-whitelist.json

fixes INTEG-2253
fixes INTEG-2252

feat(desc): updating desc

---

data/tokens.json

also fixes INTEG-2294
Also fixes INTEG-2292

feat(USDe): allows the hardcoding to USDT

---

data/price-feeds.json
data/tokens.json

FIXES INTEG-2278
adding feed and token
collateral pricing will be handled externally for now.

feat(pt): add token and feed

---

data/oracle-prices.json

DL price PAXG properly! so we need to remove the manual pricing we had

feat(PAXG): removing the old gold pricing

---

data/price-feeds.json
data/tokens.json

DL is pricing it!  ✅ 
waiting for backed clearance before whitelisting the oracle feed

feat(wbCOIN): whitelisting asset + oracle clearance

---

data/price-feeds.json
data/tokens.json

fixes INTEG-2339
fixes INTEG-2353
fixes INTEG-2354
fixes INTEG-2358
fixes INTEG-2356

feat(steak): clearing los of things

---

data/curators-whitelist.json
data/price-feeds.json
data/tokens.json
data/vaults-whitelist.json

- logo coming soon, prepared the path ✅ 
fixes INTEG-2388 
fixes INTEG-2387
fixes INTEG-2392

feat(9summits): whitelisting vault & markets

---

data/tokens.json

feat(USDL): allowing hardcoding to USDT

---

data/vaults-whitelist.json

feat(steakhouse): whitelsiting lvl vault

---

data/price-feeds.json

1 USDC staked in syrup at maturity

feat(steakhouse): pt feed clearance

---

data/tokens.json

feat(tokens): adding logo

---

data/price-feeds.json

feat(pt-token): oracle clearance

---

data/price-feeds.json
data/tokens.json

also fixes INTEG-2402
also fixes INTEG-2399

feat(Steakhouse markets): oracles clearance and tokens whitelisting

---

data/price-feeds.json
data/tokens.json

FYI:
https://oracles.morpho.dev/oracle-decoder?network=1&oracle=0x62b375616E934Fd995D11eD074B918Ce3C67c7d1&collateral=0x87C9053C819bB28e0D73d33059E1b3DA80AFb0cf&loan=0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48&marketId=0x921afaedabc6597ac12ce8c0f1a8d562a2326c401ef1e3c77e861988890fc3ce

feat(mRe7yield): market clearance

---

data/vaults-whitelist.json

test vault on unichain with idle market only

feat(test): whitelisting test vault

---

data/vaults-whitelist.json

**FIXES INTEG-2463**
[WBTC Vault Bridge
](https://app.morpho.org/ethereum/vault/0x812B2C6Ab3f4471c0E43D4BB61098a9211017427/vault-bridge-wbtc)
**FIXES INTEG-2464**
[WETH Vault Bridge
](https://app.morpho.org/ethereum/vault/0x31A5684983EeE865d943A696AAC155363bA024f9/vault-bridge-weth)
**FIXES INTEG-2465**
[USDT Vault Bridge
](https://app.morpho.org/ethereum/vault/0xc54b4E08C1Dcc199fdd35c6b5Ab589ffD3428a8d/vault-bridge-usdt?subTab=risk)
curators/owners addresses in the list
3D timelock OK
vaults seeded

feat(vaults): add bridge vaults

---

data/curators-whitelist.json
data/vaults-whitelist.json

**FIXES INTEG-2446**
MEV Capital wETH - 0x3f93576d13091bfBF6825F7421eF33cC353dC433
**FIXES INTEG-2483**
MEV Capital USDC - 0xc063181747E56c034ac14dC82DB663409566Fdf6
~~**FIXES INTEG-2447**
MEV Capital USDC - 0xa1b7522c0bB5eD1C2886aa857c357c7bD6d861d4~~
CANCELLED

feat(wl): MEV vaults

---

data/price-feeds.json
data/tokens.json
data/vaults-whitelist.json

**FIXES INTEG-2493**
Clears [PT-USDS-14AUG2025/DAI](https://app.morpho.org/ethereum/market/0xa458018cf1a6e77ebbcc40ba5776ac7990e523b7cc5d0c1e740a4bbc13190d8f/pt-usds-14aug2025-dai?subTab=advanced) (token + linear feed)
**FIXES INTEG-2466**
Update SolvBTC.BBN to xSolvBTC
Also removes u test vault

feat(updates): various updates

---

data/curators-whitelist.json
data/vaults-whitelist.json

**FIXES INTEG-2494**
rounded logo

feat(k3): update logo

---

data/curators-whitelist.json
data/vaults-whitelist.json

**FIXES INTEG-2480**
Re7 USDC - 0xa48f8A10F16bB50A588606553D9fE7338050f8Cd
**FIXES INTEG-2481**
Re7 WETH - 0x6af5E46456A8ac80BB53a02799965DEF99c26e52
**FIXES INTEG-2482**
Re7 USDT - 0x2c0F7e917257926BA6233B20DE19d7fe3210858C

feat(wl): re7 vaults

---

data/curators-whitelist.json

https://morpholabs.slack.com/archives/C08RVGAUWUV/p1748864182760379
Fixes: INFRA-762

fix(curators): add steakhouse on unichain

---

data/curators-whitelist.json
data/tokens.json

**FIXES INTEG-2519**
update re7 whitelisted address for unichain
**FIXES INTEG-2520**
Updating wstETH name -> removing caps

feat(curator): update address

---

data/tokens.json

**FIXES INTEG-2505**
remove caps from logo link

feat(logo): update xsolvbtc logo link

---

data/price-feeds.json
data/tokens.json

feat(pt): whitelisting pt token

---

data/vaults-whitelist.json

FIXES INTEG-2534
Updating re7 url on vault whitelist

feat(url): update re7 url

---

data/vaults-whitelist.json

**FIXES INTEG-2604**
Update [TAC USDC vault](https://app.morpho.org/ethereum/vault/0x1E2aAaDcF528b9cC08F43d4fd7db488cE89F5741/tac-usdc) description to reflect TAC branding
**FIXES INTEG-2605**
Update [TAC ETH vault](https://app.morpho.org/ethereum/vault/0x0bB2751a90fFF62e844b1521637DeD28F3f5046A/tac-eth) description to reflect TAC branding

feat(vaults): desc update

---

data/price-feeds.json

Market: https://app.morpho.org/base/market/0x20cd987b0b92365b549e17b6c5200ecc24032e4423a1badd7cc99d45fbce3c05/pt-lbtc-scaled18-25sep2025-cbbtc

feat(PT): whitelisting feed linear discount

---

data/price-feeds.json
data/tokens.json

feat: add Pendle PT-USR-4SEP2025 token and price feed data

---

data/price-feeds.json
data/tokens.json

**FIXES INTEG-2614**
[sUSDEsUSDS/USDC](https://app.morpho.org/ethereum/market/0xe0800b3f305b167e65738adc54e03d48c7bf4fb03af2734b4a72034852ba4a7a/susdesusds-usdc) market
only sUSDEsUSDS token clearance (logo has not been uploaded - waiting better format)
oracle decoder not passing - MorphoChainlinkOracleV2 not used - feed warnings remain
**FIXES INTEG-2624**
[PT-mMEV-31JUL2025/USDC](https://app.morpho.org/ethereum/market/0x89613b0381d73cf379c507bf731cd79f9bd06c28372284b7559fc47fb2873ba7/pt-mmev-31jul2025-usdc)
oracle decoder ✅
token cleared (tried the rounded ish logo - will amend if does not look good on the app)
FIXES INTEG-2637
[mF-ONE/USDC](https://app.morpho.org/ethereum/market/0xef2c308b5abecf5c8750a1aa82b47c558005feb7a03f4f8e1ad682d71ac8d0ba/mf-one-usdc)
token cleared but not priced …

Feat(markets): clearing 3 markets

---

data/vaults-whitelist.json

**FIXES INTEG-2623**
[Yearn OG USDC vault](https://app.morpho.org/ethereum/vault/0xF9bdDd4A9b3A45f980e11fDDE96e16364dDBEc49/yearn-og-usdc?subTab=risk)
3D timelock ✅
Owner = Safe ✅
Owner address WL ✅
vault seeded ✅

feat(wl): yearn vault

---

data/price-feeds.json

Updating pt-iusd feed vendor to Pendle

feat(feed): update vendor

---

data/exchange-rates.json
test/json/validation/exchange-rates.test.ts

This PR resync this file with the one in api repo in order to prepare for migration.

feat(exchange-rates): update exchange rates

---

data/tokens.json

Add wstETH and WETH asset for testing purpose.

feat(token): add weth and wsteth

---

data/tokens.json

https://arbiscan.io/address/0x40bd670a58238e6e230c430bbb5ce6ec0d40df48

feat(token): add morpho token

---

data/curators-whitelist.json

Add August as Whitelisted curator

feat(curator): add august

---

data/vaults-whitelist.json

**FIXES INTEG-2999**
Update Relend vaults description (remove 'units' mentions)

feat(relend): update vaults desc

---

data/curators-whitelist.json

Add Avantgarde addresses on Arbitrum

feat(addresses): add arbitrum addresses

---

data/vaults-whitelist.json

Reverts morpho-org/morpho-blue-api-metadata#365

Revert "Vault Whitelisting: 0x704761B6280BfABC7E397EfD34Fc15cd3b527d7D - RE7 Labs - 09-01-2025"

---

data/curators-whitelist.json

**FIXES INTEG-3118**
Add USDU DAO owner address on Ethereum

feat(owner): add usdu dao address

---

data/curators-whitelist.json

Add Felix addresses on HyperEVM

feat(curator): add felix addresses on hyperevm

---

data/tokens.json

Reverts morpho-org/morpho-blue-api-metadata#491

Revert "fix(tokens): remove hyperevm tokens temporary"
